// <auto-generated />
using System;
using AuthNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthNexus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthNexusDbContext))]
    partial class AuthNexusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Applications.ApplicationProfileRecord", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_name");

                    b.Property<short>("Audience")
                        .HasColumnType("smallint")
                        .HasColumnName("application_audience");

                    b.Property<string>("AuthenticationPolicyReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authentication_policy_reference");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_locale");

                    b.Property<short>("Mode")
                        .HasColumnType("smallint")
                        .HasColumnName("application_mode");

                    b.Property<string>("RegistrationSchemaReference")
                        .HasColumnType("text")
                        .HasColumnName("registration_schema_reference");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("application_type");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("ApplicationId")
                        .HasName("pk_application_profiles");

                    b.ToTable("application_profiles", "applications", t =>
                        {
                            t.HasCheckConstraint("ck_application_profiles_application_id_not_empty", "application_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_application_profiles_audience", "application_audience IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("ck_application_profiles_locale_not_blank", "btrim(default_locale) <> ''");

                            t.HasCheckConstraint("ck_application_profiles_mode", "application_mode IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_application_profiles_name_not_blank", "btrim(application_name) <> ''");

                            t.HasCheckConstraint("ck_application_profiles_policy_reference_not_blank", "btrim(authentication_policy_reference) <> ''");

                            t.HasCheckConstraint("ck_application_profiles_schema_reference_not_blank", "registration_schema_reference IS NULL OR btrim(registration_schema_reference) <> ''");

                            t.HasCheckConstraint("ck_application_profiles_tenant_id_not_empty", "tenant_id IS NULL OR tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_application_profiles_type", "application_type IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("ck_application_profiles_version_not_empty", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Applications.ApplicationRedirectUriRecord", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uri");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("ApplicationId", "RedirectUri")
                        .HasName("pk_application_redirect_uris");

                    b.HasIndex("ApplicationId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_application_redirect_uris_application_sort_order");

                    b.ToTable("application_redirect_uris", "applications", t =>
                        {
                            t.HasCheckConstraint("ck_application_redirect_uris_application_id_not_empty", "application_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_application_redirect_uris_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_application_redirect_uris_uri_not_blank", "btrim(redirect_uri) <> ''");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Audit.SecurityEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NetworkSummary")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("network_summary");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("UserAgentSummary")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent_summary");

                    b.HasKey("EventId")
                        .HasName("pk_security_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_security_events_correlation_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_security_events_occurred_at");

                    b.HasIndex("ApplicationId", "Timestamp")
                        .HasDatabaseName("ix_security_events_application_occurred_at");

                    b.HasIndex("TargetUserId", "Timestamp")
                        .HasDatabaseName("ix_security_events_target_user_occurred_at");

                    b.ToTable("security_events", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_security_events_correlation_id", "correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_security_events_event_id", "event_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_security_events_metadata_object", "jsonb_typeof(metadata) = 'object'");

                            t.HasCheckConstraint("ck_security_events_optional_ids", "(actor_user_id IS NULL OR actor_user_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (target_user_id IS NULL OR target_user_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (application_id IS NULL OR application_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (tenant_id IS NULL OR tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (session_id IS NULL OR session_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_security_events_result", "result BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_security_events_type", "event_type IN ('registration_requested', 'registration_completed', 'email_verification_sent', 'email_verified', 'phone_verification_sent', 'phone_verified', 'login_succeeded', 'login_failed', 'login_throttled', 'mfa_required', 'mfa_succeeded', 'mfa_failed', 'password_reset_requested', 'password_reset_completed', 'password_changed', 'passkey_added', 'passkey_used', 'passkey_removed', 'totp_added', 'totp_removed', 'recovery_code_used', 'external_identity_linked', 'external_identity_unlinked', 'session_created', 'session_revoked', 'logout_all', 'security_step_up_required', 'security_step_up_completed', 'account_temporarily_protected', 'account_suspended', 'account_deletion_requested', 'account_deleted', 'authorization_denied', 'policy_draft_created', 'policy_changed', 'policy_approved', 'provider_unavailable')");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Authentication.AuthenticationTransactionRecord", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<short>("Purpose")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("TransactionId")
                        .HasName("pk_authentication_transactions");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_authentication_transactions_application_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_authentication_transactions_correlation_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_authentication_transactions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_transactions_user_id");

                    b.HasIndex("State", "ExpiresAt")
                        .HasDatabaseName("ix_authentication_transactions_state_expires_at");

                    b.ToTable("authentication_transactions", "authentication", t =>
                        {
                            t.HasCheckConstraint("ck_authentication_transactions_application_id", "application_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_authentication_transactions_correlation_id", "correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_authentication_transactions_expiry_state", "(state = 7 AND state_changed_at >= expires_at) OR (state <> 7 AND state_changed_at < expires_at)");

                            t.HasCheckConstraint("ck_authentication_transactions_initial_state", "state <> 1 OR state_changed_at = created_at");

                            t.HasCheckConstraint("ck_authentication_transactions_lifetime", "expires_at > created_at AND state_changed_at >= created_at");

                            t.HasCheckConstraint("ck_authentication_transactions_purpose", "purpose BETWEEN 1 AND 14");

                            t.HasCheckConstraint("ck_authentication_transactions_state", "state BETWEEN 1 AND 8");

                            t.HasCheckConstraint("ck_authentication_transactions_tenant_id", "tenant_id IS NULL OR tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_authentication_transactions_terminal_state", "(state = 5 AND completed_at IS NOT NULL AND completed_at = state_changed_at AND failed_at IS NULL) OR (state = 6 AND failed_at IS NOT NULL AND failed_at = state_changed_at AND completed_at IS NULL) OR (state NOT IN (5, 6) AND completed_at IS NULL AND failed_at IS NULL)");

                            t.HasCheckConstraint("ck_authentication_transactions_transaction_id", "transaction_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_authentication_transactions_user_id", "user_id IS NULL OR user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_authentication_transactions_version", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Identity.UserAccountRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("UserId")
                        .HasName("pk_user_accounts");

                    b.ToTable("user_accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_state", "state IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("ck_user_accounts_state_changed_at", "(state = 1 AND state_changed_at = created_at) OR (state <> 1 AND state_changed_at >= created_at)");

                            t.HasCheckConstraint("ck_user_accounts_user_id_not_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_user_accounts_version_not_empty", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Notifications.NotificationOutboxMessageRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<byte[]>("DestinationCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("destination_ciphertext");

                    b.Property<int>("DestinationFormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("destination_format_version");

                    b.Property<string>("DestinationProtectionKeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("destination_protection_key_id");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_failure_code");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_type");

                    b.Property<byte[]>("PayloadCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_ciphertext");

                    b.Property<int>("PayloadFormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_format_version");

                    b.Property<string>("PayloadProtectionKeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_protection_key_id");

                    b.Property<DateTimeOffset?>("PermanentlyFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("permanently_failed_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("MessageId")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_due");

                    b.HasIndex("TargetUserId", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_target_user_created_at");

                    b.ToTable("outbox_messages", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_channel", "channel BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_outbox_correlation_id", "correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_outbox_delivery_shape", "(state = 1 AND state_changed_at = created_at AND attempt_count = 0 AND last_attempted_at IS NULL AND next_attempt_at IS NOT NULL AND next_attempt_at = available_at AND delivered_at IS NULL AND permanently_failed_at IS NULL AND last_failure_code IS NULL) OR (state = 2 AND state_changed_at >= available_at AND attempt_count > 0 AND last_attempted_at IS NOT NULL AND last_attempted_at = state_changed_at AND next_attempt_at IS NOT NULL AND next_attempt_at > last_attempted_at AND delivered_at IS NULL AND permanently_failed_at IS NULL AND last_failure_code IS NOT NULL) OR (state = 3 AND state_changed_at >= available_at AND attempt_count > 0 AND last_attempted_at IS NOT NULL AND last_attempted_at = state_changed_at AND delivered_at IS NOT NULL AND delivered_at = state_changed_at AND next_attempt_at IS NULL AND permanently_failed_at IS NULL AND last_failure_code IS NULL) OR (state = 4 AND state_changed_at >= available_at AND attempt_count > 0 AND last_attempted_at IS NOT NULL AND last_attempted_at = state_changed_at AND permanently_failed_at IS NOT NULL AND permanently_failed_at = state_changed_at AND next_attempt_at IS NULL AND delivered_at IS NULL AND last_failure_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_outbox_destination_ciphertext", "octet_length(destination_ciphertext) BETWEEN 29 AND 1564");

                            t.HasCheckConstraint("ck_outbox_destination_format", "destination_format_version = 1");

                            t.HasCheckConstraint("ck_outbox_destination_key_id", "destination_protection_key_id ~ '^[A-Za-z0-9_.:-]{1,128}$'");

                            t.HasCheckConstraint("ck_outbox_failure_code", "last_failure_code IS NULL OR last_failure_code ~ '^[a-z][a-z0-9._-]{0,63}$'");

                            t.HasCheckConstraint("ck_outbox_message_id", "message_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_outbox_notification_type", "notification_type ~ '^[a-z][a-z0-9._-]{0,99}$'");

                            t.HasCheckConstraint("ck_outbox_optional_ids", "(target_user_id IS NULL OR target_user_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (application_id IS NULL OR application_id <> '00000000-0000-0000-0000-000000000000'::uuid) AND (tenant_id IS NULL OR tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_outbox_payload_ciphertext", "octet_length(payload_ciphertext) BETWEEN 1 AND 65536");

                            t.HasCheckConstraint("ck_outbox_payload_format", "payload_format_version > 0");

                            t.HasCheckConstraint("ck_outbox_payload_key_id", "payload_protection_key_id ~ '^[A-Za-z0-9_.:-]{1,128}$'");

                            t.HasCheckConstraint("ck_outbox_state", "state BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_outbox_times", "available_at >= created_at AND state_changed_at >= created_at");

                            t.HasCheckConstraint("ck_outbox_version", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Sessions.SessionRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("AuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<short?>("RevocationReason")
                        .HasColumnType("smallint")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("RotationCount")
                        .HasColumnType("integer")
                        .HasColumnName("rotation_count");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("session_secret_hash");

                    b.Property<DateTimeOffset>("SecretRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("secret_rotated_at");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("SessionId")
                        .HasName("pk_sessions");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ux_sessions_session_secret_hash");

                    b.HasIndex("ApplicationId", "State")
                        .HasDatabaseName("ix_sessions_application_id_state");

                    b.HasIndex("State", "AbsoluteExpiresAt")
                        .HasDatabaseName("ix_sessions_state_absolute_expires_at");

                    b.HasIndex("State", "IdleExpiresAt")
                        .HasDatabaseName("ix_sessions_state_idle_expires_at");

                    b.HasIndex("UserId", "State")
                        .HasDatabaseName("ix_sessions_user_id_state");

                    b.ToTable("sessions", "sessions", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_application_id", "application_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_sessions_lifetime", "authenticated_at <= created_at AND created_at < idle_expires_at AND idle_expires_at <= absolute_expires_at");

                            t.HasCheckConstraint("ck_sessions_operation_timestamps", "last_seen_at >= created_at AND last_seen_at <= updated_at AND last_seen_at < idle_expires_at AND updated_at >= created_at AND state_changed_at >= created_at AND state_changed_at <= updated_at AND secret_rotated_at >= created_at AND secret_rotated_at <= updated_at AND secret_rotated_at < idle_expires_at");

                            t.HasCheckConstraint("ck_sessions_revocation_reason", "revocation_reason IS NULL OR revocation_reason BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_sessions_rotation_count", "rotation_count >= 0");

                            t.HasCheckConstraint("ck_sessions_secret_hash", "char_length(session_secret_hash) = 43 AND session_secret_hash ~ '^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$'");

                            t.HasCheckConstraint("ck_sessions_session_id", "session_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_sessions_state", "state BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_sessions_tenant_id", "tenant_id IS NULL OR tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_sessions_terminal_state", "(state = 1 AND state_changed_at = created_at AND revoked_at IS NULL AND revocation_reason IS NULL AND expired_at IS NULL) OR (state = 2 AND revoked_at IS NOT NULL AND revoked_at = state_changed_at AND state_changed_at = updated_at AND revocation_reason IS NOT NULL AND expired_at IS NULL) OR (state = 3 AND expired_at IS NOT NULL AND expired_at = state_changed_at AND state_changed_at = updated_at AND expired_at >= idle_expires_at AND revoked_at IS NULL AND revocation_reason IS NULL)");

                            t.HasCheckConstraint("ck_sessions_user_id", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_sessions_version", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Applications.ApplicationRedirectUriRecord", b =>
                {
                    b.HasOne("AuthNexus.Infrastructure.Persistence.Applications.ApplicationProfileRecord", null)
                        .WithMany("AllowedRedirectUris")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_redirect_uris_application_profiles");
                });

            modelBuilder.Entity("AuthNexus.Infrastructure.Persistence.Applications.ApplicationProfileRecord", b =>
                {
                    b.Navigation("AllowedRedirectUris");
                });
#pragma warning restore 612, 618
        }
    }
}
